clear all;
close all;
clc;
load ('hall.mat');
[x,y]=size(hall_gray);
length=x;
sample=double(hall_gray(1:length,1:length));
sample=sample-ones(length,length)*128;
dct_sample=dct2(sample);
dct_rightzero=dct_sample;
dct_leftzero=dct_sample;
dct_rot90=dct_sample;
dct_rot180=dct_sample;
dct_T=dct_sample';
dct_rightzero(:,length-3:length)=0;
dct_leftzero(:,1:4)=0;
dct_rot90=rot90(dct_rot90);
dct_rot180=rot90(dct_rot180,2);
sample_right=idct2(dct_rightzero);
sample_left=idct2(dct_leftzero);
sample_rot90=idct2(dct_rot90);
sample_rot180=idct2(dct_rot180);
sample_T=idct2(dct_T);
imwrite(uint8(sample+ones(length,length)*128),'exe_2_3_1.png','png');
imwrite(uint8(sample_right+ones(length,length)*128),'exe_2_3_2.png','png');
imwrite(uint8(sample_left+ones(length,length)*128),'exe_2_3_3.png','png');
imwrite(uint8(sample_rot90+ones(length,length)*128),'exe_2_4_1.png','png');
imwrite(uint8(sample_rot180+ones(length,length)*128),'exe_2_4_2.png','png');
imwrite(uint8(sample_T+ones(length,length)*128),'exe_2_4_3.png','png');