# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message2Server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MessageType_pb2 as MessageType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14Message2Server.proto\x12\x08protobuf\x1a\x11MessageType.proto\"\xb3\x01\n\tPlayerMsg\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12-\n\x0cstudent_type\x18\x02 \x01(\x0e\x32\x15.protobuf.StudentTypeH\x00\x12-\n\x0ctricker_type\x18\x03 \x01(\x0e\x32\x15.protobuf.TrickerTypeH\x00\x12)\n\x0bplayer_type\x18\x04 \x01(\x0e\x32\x14.protobuf.PlayerTypeB\n\n\x08job_type\"I\n\x07MoveMsg\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12\r\n\x05\x61ngle\x18\x02 \x01(\x01\x12\x1c\n\x14time_in_milliseconds\x18\x03 \x01(\x03\"C\n\x07PropMsg\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12%\n\tprop_type\x18\x02 \x01(\x0e\x32\x12.protobuf.PropType\"o\n\x07SendMsg\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12\x14\n\x0cto_player_id\x18\x02 \x01(\x03\x12\x16\n\x0ctext_message\x18\x03 \x01(\tH\x00\x12\x18\n\x0e\x62inary_message\x18\x04 \x01(\x0cH\x00\x42\t\n\x07message\"-\n\tAttackMsg\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12\r\n\x05\x61ngle\x18\x02 \x01(\x01\"\x1a\n\x05IDMsg\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\"<\n\x11TreatAndRescueMsg\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12\x14\n\x0cto_player_id\x18\x02 \x01(\x03\"/\n\x08SkillMsg\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12\x10\n\x08skill_id\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Message2Server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERMSG._serialized_start=54
  _PLAYERMSG._serialized_end=233
  _MOVEMSG._serialized_start=235
  _MOVEMSG._serialized_end=308
  _PROPMSG._serialized_start=310
  _PROPMSG._serialized_end=377
  _SENDMSG._serialized_start=379
  _SENDMSG._serialized_end=490
  _ATTACKMSG._serialized_start=492
  _ATTACKMSG._serialized_end=537
  _IDMSG._serialized_start=539
  _IDMSG._serialized_end=565
  _TREATANDRESCUEMSG._serialized_start=567
  _TREATANDRESCUEMSG._serialized_end=627
  _SKILLMSG._serialized_start=629
  _SKILLMSG._serialized_end=676
# @@protoc_insertion_point(module_scope)
